# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SCCToolForEOChild1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SCC_Dialog1(object):
    def setupUi(self, SCC_Dialog1):
        SCC_Dialog1.setObjectName("SCC_Dialog1")
        SCC_Dialog1.resize(779, 283)
        self.textBrowser = QtWidgets.QTextBrowser(SCC_Dialog1)
        self.textBrowser.setGeometry(QtCore.QRect(40, 130, 441, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.widget = QtWidgets.QWidget(SCC_Dialog1)
        self.widget.setGeometry(QtCore.QRect(510, 80, 183, 137))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SWUpdate = QtWidgets.QCommandLinkButton(self.widget)
        self.SWUpdate.setStyleSheet("")
        self.SWUpdate.setObjectName("SWUpdate")
        self.verticalLayout.addWidget(self.SWUpdate)
        self.HWUpdate = QtWidgets.QCommandLinkButton(self.widget)
        self.HWUpdate.setObjectName("HWUpdate")
        self.verticalLayout.addWidget(self.HWUpdate)
        self.SWAndHWUpdate = QtWidgets.QCommandLinkButton(self.widget)
        self.SWAndHWUpdate.setObjectName("SWAndHWUpdate")
        self.verticalLayout.addWidget(self.SWAndHWUpdate)

        self.retranslateUi(SCC_Dialog1)
        QtCore.QMetaObject.connectSlotsByName(SCC_Dialog1)

    def retranslateUi(self, SCC_Dialog1):
        _translate = QtCore.QCoreApplication.translate
        SCC_Dialog1.setWindowTitle(_translate("SCC_Dialog1", "Dialog"))
        self.textBrowser.setHtml(_translate("SCC_Dialog1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'宋体\',\'monospace\'; font-size:18pt; font-weight:600; color:#008080;\">您是否升级了软件和硬件？</span></p></body></html>"))
        self.SWUpdate.setText(_translate("SCC_Dialog1", "只有软件升级"))
        self.HWUpdate.setText(_translate("SCC_Dialog1", "只有硬件升级"))
        self.SWAndHWUpdate.setText(_translate("SCC_Dialog1", "软件和硬件都有升级"))
