# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SCCToolForEO.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SCC_MainWindow(object):
    def setupUi(self, SCC_MainWindow):
        SCC_MainWindow.setObjectName("SCC_MainWindow")
        SCC_MainWindow.resize(895, 520)
        self.centralwidget = QtWidgets.QWidget(SCC_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GO = QtWidgets.QPushButton(self.centralwidget)
        self.GO.setGeometry(QtCore.QRect(700, 450, 71, 31))
        self.GO.setObjectName("GO")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(770, 450, 71, 31))
        self.exit.setObjectName("exit")
        self.instruction = QtWidgets.QTextEdit(self.centralwidget)
        self.instruction.setGeometry(QtCore.QRect(130, 80, 621, 111))
        self.instruction.setObjectName("instruction")
        self.name = QtWidgets.QTextEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(300, 30, 241, 31))
        self.name.setObjectName("name")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(130, 200, 621, 221))
        self.textBrowser.setObjectName("textBrowser")
        SCC_MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SCC_MainWindow)
        self.statusbar.setObjectName("statusbar")
        SCC_MainWindow.setStatusBar(self.statusbar)
        self.action_GO = QtWidgets.QAction(SCC_MainWindow)
        self.action_GO.setObjectName("action_GO")
        self.action_GO_2 = QtWidgets.QAction(SCC_MainWindow)
        self.action_GO_2.setObjectName("action_GO_2")

        self.retranslateUi(SCC_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(SCC_MainWindow)

    def retranslateUi(self, SCC_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        SCC_MainWindow.setWindowTitle(_translate("SCC_MainWindow", "MainWindow"))
        self.GO.setText(_translate("SCC_MainWindow", "GO"))
        self.exit.setText(_translate("SCC_MainWindow", "exit"))
        self.instruction.setHtml(_translate("SCC_MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">使用方法：</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1、点击GO 键开始</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2、在弹出的对话框中选择对应的选项</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3、所有选项完成之后，会针对选项给出零件号、硬件号、软件号是否升级的回答</p></body></html>"))
        self.name.setHtml(_translate("SCC_MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">零件号是否升级查询工具</span></p></body></html>"))
        self.action_GO.setText(_translate("SCC_MainWindow", "点击GO"))
        self.action_GO_2.setText(_translate("SCC_MainWindow", "点击GO"))
